import = [ 
  "~/.config/alacritty/catppuccin-mocha.toml" 
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
dynamic_padding = true
startup_mode = "Maximized"

decorations = "Buttonless"

opacity = 1.0
blur = false

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 16
